name: NonProd Workflow

on:
  push:
    branches:
      - test_workflow
  pull_request:
    branches:
      - main

jobs:
  set-up-infra:
    name: "Set up Terraform"
    uses: ./.github/workflows/setup_infra.yml
    with:
      ENVIRONMENT: nonprod
    secrets:
      SVC_ACCOUNT_KEY: ${{ secrets.SVC_ACCOUNT_KEY }}
