name: Run FastAPI Tests

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: nonprod
    strategy:
      matrix:
        project: ['tagging']  # Change if you have multiple projects

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Dependencies
        run: |
          cd ${{ matrix.project }}  # Change directory to project folder
          echo "pwd"
          poetry install --no-interaction

      - name: Run Pytests
        run: |
          cd ${{ matrix.project }}
          poetry run pytest tests/  # Run tests in `tests/`
